js/damage.js
Currently Venoshock calculates 4x on "Poisoned" status due to the bonus damage calculation ocurring twice, once in the lines removed from the commit and the second time in [this check](https://github.com/Zarel/honko-damagecalc/blob/master/js/damage.js#L308).
Also the removed lines had the issue of ignoring "Badly Poisoned" status.
=> Fix Venoshock 4x effect on poison

js/calc_ab.js
By scheduling calculations to the next turn of the event loop,
this fixes the issue by which switching Gen caused some
damage ranges to display as NaN - NaN%
=> Ensure that all event listeners are run before calculations

js/damage.js
Was reviewing the SuMo update and found Ability was capitalized when it shouldn't be. Parental Bond wasn't broken but this is more concise; I tested this one in browser to make sure it's working properly.
=> Fix 'Long Reach' and 'Parental Bond' calculations

js/ap_calc.js
Now if I check Grassy Terrain in SM/XY and switch to a previous gen like DPP, Grassy Terrain recovery is still calculated.
I think the best way to prevent such a situation is to clear terrain when gen was changed, just like what we do with weather.
=> Clear terrain when gen changed

ap_calc.css, calc_bc.html, index.html, js/ap_calc.js, js/damage.js, js/data/move_data.js
Add a "z" checkbox beside move selector. If it is checked, the corresponding z-move will be used for calc, which should simplify z-move input.
This requires work of @AustinXII (in progress), which adds a z-power property to each move, and a z-move map.
Changes in detail:
1. Add a "z" checkbox beside each move (`index.html`, `calc_bc.html`), and update layout to make all views in the same line. (`ap_calc.css`)
2. Add `getZMoveName` function, which finds the proper z-move to use. Hidden Power becomes Breakneck Blitz. Special move with special z-crystal becomes special z-move (e.g. Volt Tackle with Pikanium Z becomes Catastropika). Otherwise a generic z-move is used. Generic z-moves do not force require a z-crystal or it would be too difficult to use. (`ap_calc.js`)
3. Add z-move check to …
=> Improve z-move input

js/damage.js, js/data/ability_data.js
The previous priority check
`
PriorityDamageCheck = move.hasPriority && (defAbility === "Queenly Majesty" || defAbility === "Dazzling") && (["Mold Breaker", "Teravolt", "Turboblaze"].indexOf(attacker.ability) !== -1) || (move.givesHealth && attacker.ability === "triage")
`
has many errors:
1. It should check if the attacker's ability IS NOT Mold Breaker, instead of checking attacker's ability IS Molder Breaker; in fact this is unnecessary, because if attacker's ability is Mold Breaker, the defender's ability is already set to empty there;
2. It checks Triage last with `||` operator, means if Triage is in effect then previous condition is ignored
So I rewrite the priority check, also add check for Gale Wings and Psychic Terrain (tested). The Gale Wings check has the same "full HP issue" …
=> Fix priority check

js/data/move_data.js
Endeavor is added by accident when we add z-power, but its basic data (such as power) is not added yet, it seems this causes honkalculate to crash so I added it
Do we need to implement its effect? I tried to implement it but the KO chance message is really ridiculous. Or should we remove it?
=> Add Endeavor

js/data/setdex_dpp.js, js/data/setdex_gsc.js, js/data/setdex_rby.js, js/data/setdex_rse.js, js/data/setdex_sm.js
Add usage-based sets for Pokemon in tiers where they have decent usage but no Smogon analysis. This is mainly for SM
where most analyses are still in progress, but it also fills in some gaps in old-gen lower tiers that lack full sets of
analyses and have usage stats available from the RoA Rotational ladder.
=> Add usage-based sets in place of absent analyses.

js/data/setdex_sm.js
- Update sets for CAP Pokemon to better reflect viable / common sets in the Gen 7 CAP metagame
- Fix some data errors
- Add sets for Tomohawk and Kerfluffle
=> Update CAP sets

js/damage.js
Moongeist and Sunsteel ignore the opponent's ability when calculating damage
=> Fix Sunsteel Strike and Moongeist Beam

calc_bc.html, js/ap_calc.js, js/calc_ab.js
Add terrain options to one-vs-all/all-vs-one. Changes in detail:
1. Add terrain buttons to `calc_bc.html`
2. Add `terrain-trigger` class to type/ability/item elements in `calc_bc.html`
3. Move function `isGrounded`, `getTerrainEffects` to `ap_calc.js`, so they can be used both in one-vs-one and one-vs-all
Tested
=> Add terrain options to one-vs-all

calc_bc.html, index.html, js/ap_calc.js, js/damage.js, js/damage_dpp.js, js/damage_gsc.js, js/damage_rby.js, js/damage_rse.js, js/data/move_data.js
Add "Protect" option, if checked, moves without `bypassesProtect` property with do no damage, and z-moves will get their damage reduced
Implement `isZ` as an own property of z-moves instead of adding it dynamically, so even if the user type the z-move themselves, it still works
Move Feint to gen 4 when it was introduced, and change its power in gen 5
=> Implement protect check

js/ap_calc.js, js/calc_bc.js
- properly set level to 50 if VGC
- immediately set proper level upon selecting set, to prevent useless
"level changed" popups when switching sets
=> Fix setting level based on the format

js/ap_calc.js
I'm dumb and didn't test extensively enough. Apparently getSelectedTiers is simply not defined in One vs One mode?
=> Fix reference error in 1v1 mode

js/calc_bc.js
No format being selected is the default, and there is zero feedback to the user if they click "Honkalculate" in that situiation. Perhaps they even assume that "no format selected" = "use sets from all formats".
So, here's a popover (like those that appear when the level is changed) for that.
=> Notify user if no format selected for 1vsAll calculation

js/ap_calc.js
Previously the items in ADV set options was like this, so it was proper to choose the 3rd item by default when we change to ADV;
```
0  Abra
1    Blank Set
2  Aerodactyl
3    UU Showdown Usage
...
```
Now after setdex update the ADV set options is like this, the 3rd item is no longer a valid set, so weird behavoir occurs when we change to ADV. The 1st or 4th item should be chosen by default. I currently choose the 1st item.
```
0  Abra
1    NU Showdown Usage
2    Blank Set
3  Aerodactyl
4    UU Showdown Usage
...
```
=> Fix no Pokemon is selected when change to ADV

js/damage.js
Damage calculator was calculating damage for Fluffy incorrectly. Correct calculation is that damage doubles for Fire-type moves that don't make contact and halves for moves that make contact that aren't Fire type. Reported here: https://www.smogon.com/forums/posts/7310857
=> Fluffy damage calculation fixes

js/data/move_data.js
For Zap Cannon, Rock Blast, Searing Shot and Beak Blast.
Is there a reasom the calc doesn't just grab the data files from PS? Or if offline usage is important, couldn't they be auto-generated from the PS files with a script every now and then?
=> Add missing some bullet flags

js/shared_controls.js
Currently, One vs All and All vs One crash with `TypeError: pokeInfo.find is not a function  shared_controls.js:408:23 `.
We should be looking at the forme selection when creating a pokemon from user input, not when creating one from a fixed set (when pokeInfo is a string).
=> Fix crash in 1vsAll/Allvs1 mode

js/index_controls.js
Draining HP at x4 effectiveness will make the main description text go wild to the right while the percentage of the related move goes for an additional line, ruining the view. This fix reduces `recoveryText`'s length so even if the percentage went really high, nothing would be messed up.
To understand what the issue is about, try Giga Draining with Abomasnow on a Swampert for example.
EDIT : and no, no formatting issue.
=> Fix visual disorder

js/shared_controls.js
Closes issue #182.. I guess.
In short : instead of considering 2 bits for Special and one for Speed, the Speed DVs affect 2 units of HP DVs, while the Special ones do not affect but one.
=> Switch bit weights between Special and Speed stats

index.template.html, js/moveset_import.js, js/shared_controls.js
At last it has arrived!
Given this custom set :
```
Reshiram @ Draco Plate
Modest Nature
- Fusion Flare
- Energy Ball
- Thunderbolt
- Ice Beam
```
This is what happens to the page upon successful importing (notice the new checkbox) : 
Till now, nothing fancy. But when you check the box and you wanna select a Pokémon from there.... (the white Kyurem was already there)
Our Reshiram appears.
Now the reason why a blank select value shows up first is explained in both `shared_controls`' commits.
But then, the most interesting part, when you finally click a custom set : 
_Tadaaa_
Now as a side note, I'm not quite sure if anyone agrees with the select default value being blanked for default sets. But I just hope everything goes well. 🤷‍♂️
=> TODO List task No.4

index.template.html, js/damage.js, js/damage_rby.js, js/data/item_data.js, js/data/move_data.js, js/ko_chance.js, js/shared_controls.js
_MK360 hits again_
Basically shows KO chances when using a stat-dropping move several turns in a row, with some (big) cleanups.
Commits : 
`index.template.html` : add dropdown for showing how many times this select move is used in a row.
`damage.js` : refactor + calculate stat-drop induced damage. Also handles Contrary and White Herb.
`damage_rby.js` : adding description in case a Pokémon used such a move.
`item_data.js` : refactor Multi-Attack item type detection. Somehow, no one noticed the type of the Memory held is fully mentioned in its name.
`move_data.js` : added a property for moves that drop stats, whose value is equal with by how much does a stat drop.
`shared_controls.js` : added the ability to handle - guess what - moves that drop stats by showing their select dropdown, and …
=> TODO List, task No.5

js/ko_chance.js
In those modes, move.usedTimes is undefined, which caused the exit condition of the recursion to never trigger.
Also added the "moveHits" parameter to a few calls of getKOChance.
=> Fix infinite recursion in 1vsAll/Allvs1 mode

js/shared_controls.js
More issues due to move.usedTimes not being defined, so just always set it to 1 when creating pokemon from fixed sets.
=> Fix KO chance display in All vs One mode

js/shared_controls.js
For a long time, this problem would remain unsolved.
The basic problem was that upon switching and playing around formes (most prominently between a Mega form and its "basic" one), the ability would sometimes not show up properly, and this problem would make Abomasnow (PU Showdown Usage) never get its Snow Warning despite it was listed in the abilities dropdown AND mentioned in the set ability. Now thanks to a very valuable heads-up from @AustinXII, this is now from the past.
=> Fix forme abilities

js/damage.js
Carries a little bit of the previous PR (#225).
When a Pokémon has Spectral Thief amongst its moves, the game checks first if the target has positive stats boosts. If it's the case, then these boosts are applied to the attacker, then the newly-boosted stats are refreshed (if the case applies), then the Pokémon uses the actual move.
=> Update Spectral Thief behavior

js/shared_controls.js
The first issue was caused by the structure of the poke-info box being different between 1vsAll and 1vs1 mode, so hardcoding the DOM traversal with the `parent() `calls failed in the former case. I'm not sure if there was a reason for the roundabout implementation of "find poke-info, get id from poke-info, create new selector with that id", but this should be more tolerant to changes in the structure.
The second issue was because 1vsAll mode does not have the metronome hit counter elements (someone should add those I suppose), so it threw a TypeError due to property access of a null. Using `:visible` should not have that issue.
=> Fix crashes in One-vs-All due to Metronome controls

js/ko_chance.js
Let the calc get the proper KO chance text for the defender's current HP, opposing to its max HP as it was previously.
=> Fix KO Chance Text

js/moveset_import.js
Since I had a pretty difficult time relocating the "Clear custom sets" button(s), I thought that an easier way to prevent misclicks could be showing the user a warning message that will need conscious agreement if this is the action he wanted to do.
=> Make users aware their sets might disappear

js/data/move_data.js, js/data/type_data.js
According to Bulbapedia:
1) Struggle is treated as a Normal-type move in Gen I
2) It becomes "typeless" from gen 2 ownards.
We can deduce from 1) that:
- Struggle inherits all Normal-type properties including:
-- The offense/defense relationship with other types ;
-- The type category of Normal, which is Physical (it was a thing before gen IV).
=> Fix Struggle GSC calculation

js/damage.js
Aurora Veil shouldn't stack with Reflect and Light Screen. In the previous code having both Aurora Veil and Light Screen makes their effects sum up and on the other side having Aurora Veil and Reflect together nullifies both.
=> Fix Aurora Veil interaction with Reflect and Light Screen

js/damage.js
Simple fix for this issue: https://github.com/Zarel/honko-damagecalc/issues/254
Previously, on second hits and beyond, the calculator would apply the drop modifier to the base stats, which causes it to ignore items and abilities that are affecting the attack stat such as Choice Specs. Anything that was not included in the finalMod calculations was ignored.
I replaced the raw attack with the modified attack to fix this issue.
=> Issue #254: Allow ability / item modifiers to affect moves used 2+ times

js/damage.js
It should be doing 3/4 * 1/4, not 1/4. I copied the damage calculation straight from the server code, so the rounding should be correct.
=> Fix Guardian of Alola damage through Protect

js/damage.js, js/shared_controls.js
When the set had the base forme, it was possible to switch to the other formes with a dropdown.
This did not work for the non-base formes (e.g. megas) because these don't have the formes property. Maybe the should be made to inherit their base forme's data?
Anyway, I fixed this for now by chopping off the last part of the name behind the dash, which works for all formes I think.
`getSelectOptions` was being called with three arguments despite only having two, but I suppose it didn't get noticed because the forme selection was broken anyway.
Also fixed the indentation eslint errors.
=> Fix forme selection for alternate forme sets

js/data/pokedex.js
Many of the CAP prevos were missing the canEvolve property, and some were missing entirely.
=> Correct CAP prevo data

js/data/move_data.js
It wasn't ignoring the target's boosts.
=> Fix Darkest Lariat

honkalculate.template.html, index.template.html, js/damage.js, js/shared_controls.js
This updates how the Metronome damage boost is applied according to this:
https://www.smogon.com/bw/articles/bw_complete_damage_formula
I removed the feature that attempts to calculate the damage over an estimate of turns as
1) it did not work correctly before
2) it is too complex too implement
3) I believe seeing the damage for a given turn is much more useful (you might be using the move on a different Pokémon after a few turns, stat boosts/drops may have happened inbetween turns, etc.)
I also made this independent of stat-dropping moves.
=> Make Metronome item more accurate

calc/src/mechanics/gen7.ts, calc/src/test/calc.test.ts
Fixes #308. Austin - opened this as a PR instead of just pushing because I'm not sure why there's a `defAbility` variable... `gen4.ts` just sets `defender.ability = ''`, so that's what I did here as well.
=> Fix Mold Breaker in Gen 5-7

calc/src/data/items.ts, calc/src/desc.ts, calc/src/result.ts, calc/src/test/calc.test.ts
This mostly seems to work, but it causes the UI to deform in edge cases. Not sure about whether we care or whether there's a good solution:
This also fixes recovery behavior to cap properly - recovery should be capped by the defender's HP stat (test values changed to reflect this).
=> Add support for Shell Bell

calc/src/data/moves.ts, calc/src/field.ts, calc/src/mechanics/gen3.ts, calc/src/move.ts, calc/src/test/calc.test.ts
- Doubles spread damage is 50%, not 75%
- Only Physical attacks are guaranteed a minimum of 1 before the +2
Reference: https://web.archive.org/web/20170622160244/http://upcarchive.playker.info/0/upokecenter/content/pokemon-ruby-version-sapphire-version-and-emerald-version-timing-notes.html
=> Correct Gen 3 damage calculation

calc/src/mechanics/gen8.ts
atc, def are reversed. When using BodyPress
=> fix: Body Press

calc/src/field.ts, calc/src/mechanics/gen8.ts, calc/src/pokemon.ts, src/js/shared_controls.js
`Side#isDynamaxed` seems completely wrong (its a field in the Pokemon controls, not field) and doesn't belong there in the calc. But the field has a more descriptive name, so I've switched to that.
=> Remove Side#isDynamaxed and rename Pokemon#isMax

calc/src/data/natures.ts, calc/src/stats.ts
Technically, the neutral natures are each associated with a plus and minus stat of the same value.  This would be nice to include, for lookup purposes.
I'm not 100% sure if this will break anything though, so definitely need another pair of eyes.
Associations sourced from: https://pokemondb.net/mechanics/natures
=> Populate neutral nature stat associations

calc/src/data/moves.ts
Rolling kick is herein changed to be 60 base power.
Was originally listed as 70 base power, but every source on the web (and indeed, its data entry in the Pokemon Showdown files) points to it being 60 instead.
=> Tweaking move data for Rolling Kick

calc/src/mechanics/gen78.ts
Using a Max Move on a protected target didn't show the right amount of damage, acting as if the max move was a regular move (i.e. 0 damage). Now it should be displaying the damage of the move divided by 4. I just used what was already coded for Z moves.
=> Fix Max Moves to inflict reduced damage through Protect

calc/src/move.ts, src/js/shared_controls.js
I noticed while working on adding specific EOT effects from GMax moves that those would not appear if dynamaxing a GMax forme. For example, selecting Charizard-Gmax standard set, then checking the Dynamax button, would transform Flamethrower into Max Flare instead of G-Max Wildfire.
The effect was purely visual before, so it wasn't much of an issue, but since EOT effects such as G-Max Wildfire will be added to the calculator in the near future, it would be interesting to have this behaving correctly now. This should hopefully be done now.
=> Fix display issue when using GMax formes

calc/src/mechanics/gen78.ts
Serebii and Bulbapedia disagree on the damage for expanding force.  According to Serebii, the base power is boosted by 1.5x in Psychic Terrain.  According to Bulbapedia, the terrain modifier is _replaced_ by a 2x modifier.
However, a base power increase of 1.5 results in 1.5 * 1.3 = 1.95 total damage modifier — which is very close to 2x.  Until we have clear data on exactly which is correct, I opted for 1.5 damage modifier under terrain.  This would be consistent with other moves in the Isle of Armor release, and is much closer to accurate than the calculator is returning now.
https://bulbapedia.bulbagarden.net/wiki/Expanding_Force_(move)
https://www.serebii.net/attackdex-swsh/expandingforce.shtml
Serebii and Bulbapedia both now agree that Misty Explosion is boosted by 1.5x under terrain. …
=> Tutor move damage updates

calc/.eslintrc, calc/src/mechanics/gen78.ts, calc/src/mechanics/util.ts
Based on the best science I can find, Shell Side Arm's damage category is dependant on the relative _predicted damage_ and not just the defense stats of the target pokemon.
This change matches that behaviour.  I left some notes in my implementation in case this needs following up on, once there is better info.
=> Fix Shell Side Arm's category

calc/src/field.ts, calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts, calc/src/state.ts
Fairy Aura, Dark Aura, and Aura Break currently rely on one of the two Pokemon involved in the calc using the appropriate ability. To better support partners carrying these abilities in VGC/doubles, these three ability effects have been added to the Field class.
The missing support for this functionality was brought to me by @jbmagier and I arrived at a solution following some discussion between us.
This PR simply implements the under the hood functionality for use in the @smogon/calc module, and does not implement the front end support. This functionality can be seen in use on the Pikalytics Damage Calc in the screenshots below:
=> Support field-wide Fairy Aura, Dark Aura and Aura Break when neither Pokemon uses the ability

src/index.template.html, src/js/shared_controls.js
Replicated the search capabilities of the default list to the "only show imported sets" filtered list.
It now also searches for set name and pokémon name instead of just pokémon name in that filtered mode.
Fixes Issue #427
=> Search for imported sets

src/js/shared_controls.js
Being 16-bit is more cartridge accurate and also very handy for testing damage calculations with precise BP values without relying on base power modifier chaining being accurate.
=> Change BP limit from 999 to 65535

calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts
https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/page-8#post-8199267 and https://www.smogon.com/bw/articles/bw_complete_damage_formula agree on 0x1400 and 0xC00. I'm not sure about gen 4 but it should be the same.
=> Fix Rivalry boost

calc/src/mechanics/gen4.ts
After investigation in Generation 4 speedrunning (thanks minnow), it appears that the thresholds for Gen 4 are wrong when calculating the power of Flail and Reversal.
The calculation is correct for Gen 5+, though.
=> Fix Reversal and Flail power calculation for Gen 4

calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts, calc/src/mechanics/util.ts
See similar PR done on Showdown main server; https://github.com/smogon/pokemon-showdown/pull/8003
This helps for maintenance so you don't have to pull out a calculator to convert back and forth. I don't claim that all modifiers here are accurate, but all conversions should be accurate. I did make one change beyond conversions, since I noticed it was low-hanging fruit: Auras in Gen 6 should also be 5448.
=> Convert modifiers from hex to decimal

calc/src/mechanics/gen78.ts, calc/src/test/calc.test.ts
Something about https://github.com/smogon/damage-calc/pull/439 changed how -ate abilities worked with typing; currently, whenever the move enters the function, it is already Fairy / Electric / etc. and so the check for "if you're a Normal-type move" doesn't work. To fix this, I create a new move object to check if the original move really is Normal. I'm not super sure why this worked before; probably the correct solution is to set a flag or something.
Splitting off the if statement on Reckless and Iron Fist fixes that part.
Fixes:
https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-8841109
https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-8841181
=> Gen 7/8: Fix -ate abilities, Reckless, and Iron Fist

calc/src/mechanics/gen78.ts
The Dauntless Shield check was being run after the final defense stats were calculated. I don't understand why `computeFinalStats` has to be run separately for defense and attack anyway, but yeah this is why it was bugged the whole time.
=> Fix Dauntless Shield

src/randoms.template.html
It was activating the right side button when pressed.
=> Fix left side Power Spot button in randbats calc

calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts, import/.eslintrc
Implements most of the base power issues in https://github.com/smogon/damage-calc/issues/443; I didn't want to do everything at once so it'd be easier to code review. Notably, I did not implement the Speed-based modifier chaining yet; I'll need to think about that some more and want to tackle it in a separate PR once I take care of the low-hanging fruit.
Moves with custom BP:
- Steel Roller and Poltergeist now fail earlier before even entering BP calculation
- Payback, Acrobatics, Weather Ball now no longer use hardcoded damage values
- Pursuit was changed to be a move with variable base power
- Smelling Salts and Triple Kick were added as moves with variable base power
- Gyro Ball's formula was corrected
Base Power modifiers:
- BP modifiers are now grouped by effect type (move, ability, …
=> Improve base power modifiers

calc/src/mechanics/gen78.ts
Spread damage reduction was not being applied to expanding force when the field was set to doubles
=> Fix Expanding Force in doubles

calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts, calc/src/test/calc.test.ts
Using basePower instead of move.bp to correctly apply (and not apply) technician for moves with custom bp
=> Fix Technician's interaction with custom BP moves

README.md
Was trying to use smogon\calc with @scheibo 's wonderful PKM packages, and I needed to make this change to properly do that, so I thought I would correct the example code (the example code before was ignoring the first generations argument it looks like... which meant some code was trying to access .num on a Gengar where it expected a generation). 
On another note, I also needed to change: 
'@smogon/calc/adaptable';  to instead be     '@smogon/calc/dist/adaptable.js'; 
to get my local project working properly when importing stuff from adaptable, but I assume that is just some local issue with my webpack config, so I did not put it in the docs.
=> Update README adaptable example to pass correct arguments to calculate function

calc/src/mechanics/gen78.ts
I was messing around testing something on Flapple. I noticed the damage calculation was the same on ice moves with a Yache Berry held with and without Ripen as the ability. Ripen should double the effect of all berries. So a super effective attack should deal 1/4th damage and not half damage. I believe this should fix that case assuming I understood the surrounding code in regards to the damage formula.
=> Ripen not applied to super effective berries

calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts, calc/src/mechanics/util.ts
This implements a number of fixes to calculating Speed, including:
- Speed now has a proper floor of 0; the Gyro Ball and Electro Ball edge cases are implemented to reflect this
- Speed now uses proper modifier chaining
- Lower / upper bounds are implemented on all chained modifiers; in practice, this will only end up mattering for Speed
- Applying stat boosts / drops for stat calculation in Gen 3+ now accounts for 16-bit overflow
=> Fix various Speed mechanics

calc/src/mechanics/gen3.ts, calc/src/mechanics/gen4.ts, calc/src/mechanics/gen56.ts, calc/src/mechanics/gen78.ts, calc/src/move.ts
- Correctly adjusts move category
- Uses correct moves for gens 3 and 5 (swift and earthquake respectively)
- Changes the move name in the calc description to match the move being used (so Thunderbolt will show up in the calc description if Nature Power is selected in Electric Terrain)
=> Nature Power fixes

calc/src/mechanics/gen12.ts
In gen 1, type effectiveness is individually applied to each type. This can affect the damage done, e.g. Ice Beam used against Articuno. 
https://github.com/smogon/pokemon-showdown/commit/534cd35119398a901943bc5adab0db2dc8c0f42e
=> Gen 1: Type effectiveness is applied individually

calc/src/data/species.ts, calc/src/test/gen.ts
Floette-E is unreleased but is reasonably common enough in draft that I feel adding it to the calculator would be beneficial.
It causes some test fails without the change to gen.ts and I'm not sure if there's a better solution
=> Adds Floette-Eternal

calc/src/desc.ts, calc/src/mechanics/gen78.ts, calc/src/pokemon.ts, src/index.template.html, src/js/moveset_import.js, src/js/shared_controls.js
- Adds a checkbox for Terastall types
- Allow importing sets with tera types
- Fixes a bug where `Pokemon#hasType` would not return the tera type but the original leading to bugs like Flying Iron Hands taking reduced damage from Outrage in Misty Terrain. I'm not sure if there are any negative ramifications from this change. @DaWoblefet - are there any interactions where the Pokemon's tera type is ignored?
=> Support Terastallization in the UI

calc/src/desc.ts, calc/src/mechanics/gen789.ts, src/honkalculate.template.html, src/index.template.html, src/js/shared_controls.js, src/randoms.template.html
~~They were previously in `Field` but were never initialized. I did not fix them by initializing them because they're not really `Field` properties because unlike terrains it doesn't effect every Pokemon on the field.~~
~~The aura abilities are also in `Field` (though those are actually field properties) and they're never initialized but they work because the abilities are checked in the relevant mechanics files. I could have removed them but maybe they serve a purpose I'm not aware or should serve a purpose later on down the road if there's a Dark/Fairy Aura button in the field control area.~~
=> Fix ruin abilities

src/css/main.css, src/index.template.html, src/js/shared_controls.js
Made a very small addition using the Clipboard API. I ran `npm test` locally, apparently the two failing tests are unrelated to it. Hope it works properly!
=> Add click-to-copy feature

calc/src/mechanics/gen12.ts
In Gen 1, the random factor multiplication should be skipped if the damage at that point is 1. In Gen 2, the final damage is rounded up to 1 if it is 0.
This is implemented in PS.
Deals with the issue: https://github.com/smogon/damage-calc/issues/511
=> Gens 1-2: If damage is 1, skip random factor

calc/src/mechanics/gen789.ts
Addresses the issue listed [here](https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-9460009). Also added a check which should prevent the moves listed [here](https://www.serebii.net/scarletviolet/terastal.shtml) from being upped to 60 BP. This check also prevents Wring Out and Punishment (which do not exist in Gen 9 games) from receiving a BP increase, but that should line up with the behavior exhibited by the simulator in National Dex.
Also added `(60 BP)` to the description whenever this behavior occurs.
(This is my first pull request, so I apologize if there any courtesies that I am unaware of)
=> Fix check for moves receiving a BP increase due to Tera

calc/src/mechanics/gen789.ts
Griseous Core and Griseous Orb as coded here work with both formes of Giratina, to ensure backwards compatibility with gens 7,8
=> Add Adamant Crystal, Lustrous Globe, Griseous Core effects

calc/src/mechanics/gen12.ts, calc/src/mechanics/gen3.ts, calc/src/mechanics/gen4.ts
In Gen 2, 3, and 4, when it comes to calculating the damage based on dual type effectiveness, the defensive types are reordered according to a fixed order. This can alter rounding for the computed damage, since type effectiveness multiplications are performed for each type separately.
```
[
'Normal',
'Fire',
'Water',
'Electric',
'Grass',
'Ice',
'Fighting',
'Poison',
'Ground',
'Flying',
'Psychic',
'Bug',
'Rock',
'Ghost',
'Dragon',
'Dark',
'Steel',
]
```
This array determines the type order. For example if the defending type is Type 1 = Rock, Type 2 = Ground, the game will swap them for type effectiveness matters.
However, there is an exception when the attacking type is Ice and one of the defending types if Fire. In that case, Fire will always become the second defensive type.
(We have …
=> Add type effectiveness precedence for Gen 2, 3, and 4

calc/src/mechanics/gen789.ts
Under this implementation, if the ability is a Mold Breaker ability, it will still be shown even as it is ignored, and the Ability Shield will also be shown.
=> Implement Ability Shield

calc/src/mechanics/gen789.ts, calc/src/test/calc.test.ts
Tera type is now used instead of actual type if provided, fixing a bug where Collision Course gave its boost when supereffective against the original type.
=> Fix Collision Course/Electro Drift

calc/src/mechanics/gen789.ts
* They were boosting ALL moves from their respective Pokemon rather than just STABs
=> Fix bad boolean logic from 7c621065 for Adamant Crystal, Lustrous Orb, and Griseous Orb

src/css/dark-theme.css
Changed at request of user Dravos7
https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-9578768
Changes:
- Lighten the dark background
- Make text an off-white
- Desaturate the "button selected" blue
Screenshot:
=> Dark mode restyle

src/css/main.css
Fixes problem where selected set names that were too long caused that portion of the calc to be pushed off the page
Before:
After:
=> Force word wrap on selected sets

calc/package-lock.json, calc/package.json, calc/src/data/species.ts
Doesn't pass `npm test`, would like some advice on letting the test pass since I couldn't figure out how the test works.
Calculator will still work w/ updated stats
Addresses #555 
Sources:
https://serebii.net/pokedex-sv/kleavor/
https://bulbapedia.bulbagarden.net/wiki/Kleavor_(Pok%C3%A9mon)#Base_stats
=> Add Hemogoblin & fix Kleavor's stats

src/css/dark-theme.css
Gives the Select2 dropdowns a dark style when calculator is in dark theme, as opposed to remaining white when rest of elements become dark.
Screenshots:
=> Restyled Pokemon/move dropdowns for dark mode

src/css/dark-theme.css
Now darkens buttons and checkboxes when Showdown is in dark mode.
Checkboxes are unchecked:
Checkboxes are checked:
In both instances, the unstyled buttons ("Clear Imported Sets", "Export", "Click for  Light Theme") are now visibly darker.
=> Restyled checkboxes and buttons in dark mode

src/honkalculate.template.html
These changes serve to make the Gen 9 Honkalculate UI match the 1v1 UI.
The specific changes are:
-Added Tera selector
-Added Stealth Rock button, removed Steelsurge
-Changed Hail to Snow in weather selector in Gen 9
-Added Magic Room/Wonder Room to Honkalculate (from Gens 5 - 9)
I've tested and it seems that simply copying the UI elements from the 1v1 UI seems to work without additional changes.
=> Fixes to Honkalculate UI to match 1v1 UI

src/css/dark-theme.css
Currently, when looking at the calculator in its dark theme, the bottom of the calculator (beyond the button to switch the theme from light to dark) would just be white. This somewhat defeats the purpose of having a dark theme if there will still be a large patch of white at the bottom of the page (which is much larger on mobile devices). This fixes this.
Before:
After:
Screenshots were taken on 1440p monitor and resizing the browser zoom to 80%.
=> Makes entire background dark in dark theme

calc/src/mechanics/gen789.ts, calc/src/test/calc.test.ts
Fixes https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-9716660
Resulting calc: 0 SpA Tera Water Oricorio-Pom-Pom Revelation Dance vs. 252 HP / 0 SpD Sandaconda: 254-302 (72.9 - 86.7%) -- guaranteed 2HKO after Leftovers recovery
Can create tests if needed
=> Change Revelation Dance's type when attacker has Terastallized

src/css/dark-theme.css
Currently, when you search through the dropdown, when you search for something that has no matches, it should display that there are "No matches found." However, in dark mode, the text is changed to a light color, but the background still displays as a dark background, meaning that you see white text on a white background. This fixes this issue.
Screenshot:
=> Fix "No matches found" in dark mode

src/css/main.css, src/index.template.html, src/js/index_randoms_controls.js, src/js/shared_controls.js, src/randoms.template.html
Since originally authoring the pull request that implemented this feature (https://github.com/smogon/damage-calc/pull/441), I have noticed a few ways it could be better.
**Firstly**, there is an issue when the damage calculation message has a certain length, such that the hidden element that appears on click is pushed to a second line, while no text is there. This results in the abnormality shown in the screenshots below: 
The layout is pushed down by a blank line that accommodates the hidden element.
In order to fix it, I have changed the position of the confirmation message to appear above the text. I have set its position to absolute, so it will not interfere with the rest of the layout.
Below are three screenshots of how it looks, including two extreme cases of a very short output …
=> Improve appearance of click-to-copy confirmation message

calc/src/data/items.ts
Fixes #472 
Will make sure the Enigma Berry doesn't appear twice in Gens 8 and 9.
=> Remove Enigma Berry from GSC only list

src/js/moveset_import.js
* Always exports tera type, even if not checked.
* No longer displays tera type if the same as default.
=> Export Tera type iff different than default

src/css/dark-theme.css
Currently, the buttons share their color with the background color, which makes it less visually distinct compared to them. Brightening the buttons will make it so that they are more noticeable.
Contrast ratio is 9.64:1; checked using [WebAIM's contrast checker](https://webaim.org/resources/contrastchecker/?fcolor=E4E4E4&bcolor=353535)
=> Brighten the buttons in dark mode

calc/src/mechanics/gen4.ts, calc/src/mechanics/gen56.ts, calc/src/mechanics/gen789.ts
Fixes https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-10148870
Before:
252+ Atk Choice Band Huge Power Azumarill Return vs. 252 HP / 0 Def Abomasnow: 257-303 (66.9 - 78.9%) -- guaranteed 2HKO after Leftovers recovery (without Flower Gift)
252+ Atk Choice Band Huge Power Azumarill Return vs. 252 HP / 0 Def Abomasnow: 257-303 (66.9 - 78.9%) -- guaranteed 2HKO after Leftovers recovery (with Flower Gift and sun active)
After:
252+ Atk Choice Band Huge Power Azumarill Return vs. 252 HP / 0 Def Abomasnow: 257-303 (66.9 - 78.9%) -- guaranteed 2HKO after Leftovers recovery (without Flower Gift)
252+ Atk Choice Band Huge Power Azumarill with an ally's Flower Gift Return vs. 252 HP / 0 Def Abomasnow in Sun: 385-453 (100.2 - 117.9%) -- guaranteed OHKO (with …
=> Flower Gift should stack with Huge Power

calc/src/mechanics/gen4.ts, calc/src/mechanics/gen56.ts, calc/src/mechanics/gen789.ts, calc/src/test/calc.test.ts
Fixes https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-10239710
Before:
0 SpA Mold Breaker Ampharos-Mega Dragon Pulse vs. 252 HP / 252+ SpD Iron Treads: 63-75 (16.4 - 19.5%) -- possible 8HKO
(Activate Electric Terrain)
0 SpA Mold Breaker Ampharos-Mega Dragon Pulse vs. 252 HP / 252+ SpD Iron Treads: 63-75 (16.4 - 19.5%) -- possible 8HKO
After:
0 SpA Mold Breaker Ampharos-Mega Dragon Pulse vs. 252 HP / 252+ SpD Iron Treads: 63-75 (16.4 - 19.5%) -- possible 8HKO
(Activate Electric Terrain)
0 SpA Mold Breaker Ampharos-Mega Dragon Pulse vs. 252 HP / 252+ SpD Quark Drive Iron Treads: 49-58 (12.7 - 15.1%) -- possibly the worst move ever
I think that if we used `@pkmn/data` and `@pkmn/dex`, then this code (as well as other pieces of code) can be cleaned …
=> Mold Breaker shouldn't remove abilities that don't affect direct damage

calc/src/desc.ts, calc/src/field.ts, calc/src/mechanics/gen789.ts, calc/src/state.ts, calc/src/test/calc.test.ts, src/index.template.html, src/js/shared_controls.js, src/randoms.template.html
An ally's Steely Spirit will also stack with an attacker's own Steely Spirit (in other words, the two Steely Spirits will stack).
Evidence: https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8320847
=> Add support for Steely Spirit from an ally

src/js/shared_controls.js
The randbats sets use 3 letter stat names instead of the calc's regular 2 letter stat names, which caused stuff like min atk/spe and lowered hp evs to not get applied.
=> Fix EVs/IVs not getting used from randbats sets

calc/src/mechanics/gen789.ts, calc/src/test/calc.test.ts
Fixes https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/page-41#post-10458221
Essentially, when Protosynthesis and Quark Drive are activated via sun and Electric Terrain, respectively. the damage of Poltergeist and Knock Off should not be reduced. This PR fixes that and adds tests for this behavior.
=> Fix Poltergeist/Knock Off + Protosynthesis/Quark Drive interaction
