smogon/damage-calc

- ap_calc.css
- index.html
- js/moveset_import.js
Added moveset import functionality.
Due to the new layout of the calc, the field for the moveset import is now placed below the rest of the calc, instead of beside it (like in my version). I wasn't sure how to fix it without screwing up the whole layout, so I just left it like this.
> Moveset Import Functionality

- js/damage.js
These fixes are already committed to https://github.com/augmt/gen6-damage-calc; I had thought at the time that it was the official one.
> Fix some miscalculations: Auras, Fur Coat, and Weather 

- js/data/move_data.js
Added all damaging Gen3 moves and fixed various other moves
> Add and Fix Multiple Moves

- js/data/pokedex.js
> Fix pokedex error

- calc_bc.html
- index.html
- js/ap_calc.js
- js/damage.js
looks like this: https://gyazo.com/5df7dc0fc3cdb4f7d1053d4d53f41f6b
> Add a friend guard option and allow PU to be used in OnevsAll and AllvsOne

- js/data/setdex_xy.js
Took a bit longer than expected as there wasn't enough set changes on smogon to make a PR last week
> Various set updates

- js/data/move_data.js
I only added the ones that were "viable"
> Add some non damaging moves

- js/data/setdex_xy.js
Finally got around to writing something that could generate this from
the new smogon api. I'll try to run it monthly-ish from now on.
> Update XY setdex.

- js/data/setdex_xy.js
- Fix forme names to match pokedex.js
- Fix import of Mimes and Farfetch'd
- Add sets for CAP and AG metas
> Fix issues with XY setdex import

- ap_calc.css
- calc_bc.html
- index.html
- js/ap_calc.js
- js/calc_ab.js
- js/calc_bc.js
> Support reporting damage in 48ths

- js/data/move_data.js
> Fix crash in move_data.js

- ap_calc.css
- index.html
old: https://gyazo.com/3c7c2ea62cad590ee7bc01d0e3205623
new:  https://gyazo.com/ea804390be7d4cc4e05ee6766b846762
> Improve button looks and make sure big-text alignment is left

- js/damage.js
#84 Implement: Added water-type dmg boost of ability "Water Bubble"
> Fixed a missing mechanism of "Water Bubble" ability

- js/damage.js
According to Serebii.net and several sites, the power boost of Aerilate, Pixilate, Refrigerate and Galvanize has been decreased from 30% to 20%.
> Update Aerilate-like abilities

- js/data/pokedex.js
Noticed Alolan Muk is missing and wanted to add him in.
> Added Muk-Alola

- js/calc_ab.js
> Add isGrounded function

- js/ap_calc.js
- js/calc_ab.js
Autoset terrain if a surge ability is selected.
Also fixed a small bug in terrain transition: status list won't be enabled if change Misty Terrain to Electric Terrain.
> Add autoset terrain feature

- js/damage_rse.js
Reverts Zarel/honko-damagecalc#96
> Revert "Fix: remove old buildDescription function"

- calc_bc.html
- index.html
- js/ap_calc.js
- js/calc_ab.js
- js/calc_bc.js
- js/data/ability_data.js
- js/ko_chance.js
Also add Liquid Ooze
Heal (or damage if attacker has Liquid Ooze) defender if attacker is seeded
> Implement Leech Seed recovery

- js/data/move_data.js
> Fix Acid Downpour Typing

- js/calc_bc.js
> Fix sorting by damage in honkalc

- js/data/move_data.js
Also turned a handful of double quotes into single ones because that's what all the other strings are using.
> Add missing contact flags and Z move powers

- js/data/setdex_sm.js
> Fix Mollux's EV spread

- index.html
- js/ap_calc.js
- js/damage.js
- js/data/ability_data.js
In particular, the base power never gets affected by Technician. https://www.smogon.com/forums/threads/3586701
Note Bulbapedia contradicts itself: some pages say half power, others say half damage, which may have contributed to the confusion.
> Bulldoze and Earthquake halve damage, not base power, in Grassy Terrain

- js/damage.js
Similarly for Shadow Shield, Teravolt and Turboblaze; I added Full Metal Body in for completeness although I don't think it affects the damage in this case.
Also, no spurious changes this time!
> Prism Armor should ignore Mold Breaker

- ap_calc.css
- calc_bc.html
- index.html
> Improve accessibility for screen readers part 2

- honkalculate.html
- index.html
- js/honkalculate_controls.js
- js/index_controls.js
Some links and references are broken after rename
> Fix broken links and references

- js/shared_controls.js
@AustinXII I took a look and I think this will do what you wanted for https://github.com/Zarel/honko-damagecalc/pull/165
> Fix searching for Megas

- js/shared_controls.js
Fixes https://github.com/Zarel/honko-damagecalc/issues/169
> Fix searching for Tapus

- js/data/move_data.js
Was checking on Bulbapedia for moves that drain HP (for #121 issue number 6) , and didn't find this one when looking it up in the moves search in the calculator.
> Add Parabolic Charge

- js/data/move_data.js
- js/honkalculate_controls.js
- js/index_controls.js
- js/ko_chance.js
this is a WIP I'm going to add all the relevant moves, but yay!
> Improve KO chance 

- index.template.html
- js/moveset_import.js
Provides a button to clear custom sets once not needed anymore.
> TODO List #8

- js/damage.js
> Fix spikes breaking Multiscale

- js/index_controls.js
It took me less than 20 days, I must recognize. But well, let me demonstrate what will happen : 
The left Abomasnow's Blizzard will show up. Nothing unusual.
The right Abomasnow's Blizzard will show up, because it is recognized as the Pokémon who attacks first.
Its Giga Drain will show up, since it is the strongest move (x4 effectiveness, 100% - 100% draining, etc.)
Its Blizzard is shown back.
The view is switched back into the right Abomasnow's modified Giga Drain
Deoxys' Superpower is automatically shown since : 
- Deoxys-Attack is faster than Abomasnow
- Superpower deals the most damage on Abomasnow
(side note : probably should cap shown damage amount as well ?)
> Show faster Pokémon's strongest move (fix issue #130)

- honkalculate.template.html
- index.template.html
I think this could be useful since sometimes for Natures that are not often seen one does not remember well what it does.
And for newbies it's definitely a useful resource, instead of having to check another website in the meantime.
Most other calcs have it, and it saves time at no cost, so here it is.
> Update dropdown Nature menus with help (e.g.: "Adamant (+Atk/-SpA)")

- index.template.html
As per issue identified here: http://www.smogon.com/forums/threads/3593546/page-3#post-7620768
> Fix Nature Drop-down

- js/damage.js
If the Pokémon has Simple, make him pay double the lowering for stat-dropping moves.
> Add Simple for multi-turn moves

- js/damage.js
Sorry for the inconvenience caused.
> Fix diverse issues related to multi-turn moves

- js/ko_chance.js
> Fix Z-moves

- js/damage.js
- js/ko_chance.js
Deals with damage calculation inaccuracy and defender-helping stuff (Leftovers, gained Leech Seed health) text not showing up.
I know everyone is getting fed up, this was my whole fault, I have to concede.
> Additional fix

- js/damage.js
- js/data/item_data.js
- js/ko_chance.js
ignore all the separate commits I made, I was trying to change our code so it was consistent with yours and I KEPT STUFFING UP lol
> added +1 all stats button

- index.template.html
- js/moveset_import.js
- js/shared_controls.js
> Create separate custom list selectors

- js/shared_controls.js
> Fix calc crash if Pokémon doesn't hold any item

- js/damage.js
- js/data/move_data.js
- js/data/pokedex.js
- js/shared_controls.js
Didn't think adding one move would require that much editing.. Glad it's done, though!
> Add Nature's Madness, fix Eviolite

- js/data/pokedex.js
Fixes this: https://www.smogon.com/forums/threads/3593779/post-7693409
> Fix Eviolite not working on Morelull

- honkalculate.template.html
- index.template.html
- js/shared_controls.js
- shared_controls.css
Adds a little cute health bar that displays how would HP appear, according to the health percent / health amount input.
The only thing I'm not quite sure of would be the color used to the "lower than the half amount" yellow, as well as from which percentage does the bar start turning red.
> Add health bar

- js/data/pokedex.js
https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator-request-thread.3593779/page-10#post-7800853
> Set canEvolve: true for Machoke

- js/data/pokedex.js
Poipole, Cutiefly, Bagon, Carvanha, Darumaka, Remoraid, Sandygast, Shieldon
> update canEvolve for multiple pokemon

- js/moveset_import.js
> Fix proper ability not being imported on creation of custom set

- js/damage.js
It's only physical if Atk > SpA, not if Atk >= SpA.
> Fix Photon Geyser damage type for equal Atk/SpA

- js/moveset_import.js
Each color of Florges is considered a different mon for showdown. Adding suport for all color variants.
> Adds florges variants

- js/data/setdex_sm.js
The HP property was wrongly capitalized.
> Fix EVs on Jumbao sets

- js/data/item_data.js
This is minor but good to be fixed
https://bulbapedia.bulbagarden.net/wiki/Houndoominite
> Fix typo Houndoomite -> Houndoominite

- honkalculate.template.html
- index.template.html
- js/damage.js
- js/damage_dpp.js
- js/damage_gsc.js
- js/damage_rby.js
- js/damage_rse.js
- js/data/ability_data.js
- js/shared_controls.js
I've added the following features to the Damage Calc:
- calculating and displaying the final speed stat in all gens
- a toggle for the Battery ability
- a toggle for the Tailwind field effect
- a hide-able toggle that controls abilities with odd activation conditions
> Ability Toggles & Speed Calcs Upgrade - 3/14/19

- js/shared_controls.js
I don't know why we bothered with all that complex logic when we literally have the correct forme name available from the user's selection.
> Fix automatic selection of correct alt forme

- src/honkalculate.template.html
- src/index.template.html
- src/js/shared_controls.js
> Add Google Analytics tracking code

- calc/src/desc.ts
- calc/src/mechanics/gen7.ts
- calc/src/mechanics/gen8.ts
Due to `gen7.ts#calculateModern` and `gen8.ts#calculateModern` having the same name, Gen 7's function would still be used when `gen == 8`.
This also adds/fixes Punk Rock.
> Fix Gen 8 using Gen 7's calculator

- calc/src/mechanics/gen8.ts
- calc/src/mechanics/util.ts
- src/js/shared_controls.js
It is not a 1.5x damage boost, it just gives +1 on switchin.
(I assumed there was a reason all these boost-generating ability checks are separate functions, so I made a separate one as well)
> Fix Intrepid Sword

- calc/src/data/species.ts
Even though it has no coded evolutions it can still use eviolite, which is why i added `canEvolve: true,`
> Add Slowpoke-Galar

- calc/src/mechanics/gen8.ts
Most changes are VS Code formatting changes.
> Fix Foul Play description issue

- calc/src/desc.ts
- calc/src/field.ts
- calc/src/state.ts
- src/index.template.html
- src/js/shared_controls.js
The goal is to implement the special EOT effects caused by various G-Max Moves, namely:
* G-Max Wildfire/Volcalith (1/6 max HP damage), 
* G-Max Finale (1/6 max HP restored), 
* G-Max Sandblast/Centiferno (Sand Tomb/Fire Spin effect).
For now, only the Wildfire effect is implemented, and using G-Max Wildfire doesn't activate it yet.
> Add support of special properties of GMax moves 

- calc/src/mechanics/gen78.ts
Reverts smogon/damage-calc#401
> Revert "Fix Triple Axel's base power boost"

- calc/src/mechanics/gen78.ts
It just raises Defense stage by 1, like using Defense Curl. It's certainly doesn't always boost it in Grassy Terrain, hahaha
> Dauntless Shield is not a defense modifier

- src/js/moveset_import.js
I redid it, and it looks better now (only 1 commit) I hope. I closed the previous PR.
> fixing the export bug

- src/js/moveset_import.js
Fix for issues #424 and #425. 
Didn't seem like very urgent problems but both were very easy to fix so I did it anyway.
> Export import bugfix

- src/css/main.css
- src/index.template.html
- src/js/moveset_import.js
Added a new Text Field to simplify the process of naming the imported pokemon sets. This should not interfere with any current functionatility but will provide a new way of naming all the imported sets at once.
> New TextField for naming the imported sets

- calc/src/mechanics/gen78.ts
I modularized the functions in this file so that one can individually calculate base power modifiers, attack modifiers, and whatnot.
I also fixed the bug of neuroforce being added to the base power modifiers.
> Modularize the Gen 7 & 8 mechanics page

- calc/src/mechanics/gen3.ts
> Double Facade base power when poisoned, paralyzed or burned

- calc/src/move.ts
I've discovered that Karate Chop didn't always crit for Gen 1.
> Karate chop should crit

- calc/src/field.ts
- calc/src/mechanics/gen4.ts
- calc/src/mechanics/gen56.ts
- calc/src/mechanics/gen78.ts
- calc/src/mechanics/util.ts
- calc/src/state.ts
- src/index.template.html
- src/js/shared_controls.js
- src/randoms.template.html
Hope I did it right, first time doing this significant of an addition to the calc.
> Implement Magic Room and Wonder Room

- calc/src/desc.ts
- calc/src/mechanics/gen56.ts
- calc/src/mechanics/gen78.ts
- calc/src/mechanics/util.ts
apparently applying it in `computeFinalStats` doesn't work (probably should've tested that before i added it lol)
> Fix Wonder Room

- calc/src/mechanics/gen56.ts
- calc/src/mechanics/gen78.ts
> Fix Utility Umbrella & Primal Weather move nullifying

- src/js/moveset_import.js
It previously crashed when trying to import sets of SV Pokemon
> Fix 'Import' button

- calc/src/field.ts
- calc/src/mechanics/gen78.ts
- calc/src/mechanics/util.ts
- calc/src/state.ts
Implements the following:
- Snow increases physical defense in generation 9
- Protosynthesis & Quark Drive
- The four Treasures of Ruin abilities
> Add support for new abilities and snow weather

- calc/src/mechanics/gen78.ts
- calc/src/mechanics/util.ts
- calc/src/pokemon.ts
- calc/src/state.ts
- Adds teraType to Pokemon class
- Accounts for teraType in STAB calculation
- Accounts for teraType in resistance calculation
You might want to double-check especially the resistance math.  I am not confident I captured all edge cases there.
> Add Terastallization support

- calc/src/mechanics/gen789.ts
- calc/src/pokemon.ts
Regression caused by 151ef66e14ce9295efd04bed3b1f64ae9b59a45c
> Fix tera not keeping original STABs

- calc/src/move.ts
- src/js/shared_controls.js
as per https://github.com/smogon/damage-calc/pull/458#discussion_r693382847
> Fix interaction between Grip Claw and Multi-Hit Moves

- calc/src/desc.ts
- calc/src/test/calc.test.ts
This should resolve #516.
I added a test for the draining interactions near the other draining interaction tests. I did not add a test for the leech seed interaction, though, since I wasn't sure where it would go.
> Implement Big Root Interactions with Draining Moves

- calc/src/pokemon.ts
- calc/src/state.ts
Added no UI for this, can add it later if there's demand for it.
> Add dynamax level support

- src/index.template.html
The buttons did work but everything except the Snow button would not be highlighted when selected.
> Fix weather buttons in Gen 9

- calc/src/mechanics/gen789.ts
It works correctly in PS, but isnt implemented in the damage calc. See this post https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-9625220
This is my first time trying this, thankie in advance.
> Ruin Pokemon are immune to their own Ruin effects

- src/js/dark-theme-toggle.js
Simple accessibility feature to utilize dark mode features on page load.
> Automatic detect dark mode setting. 

- calc/src/mechanics/gen4.ts
- calc/src/mechanics/gen56.ts
- calc/src/mechanics/gen789.ts
https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-9725369
> Struggle should be unaffected by Normalize

- calc/src/mechanics/gen789.ts
Make Hard Press 100BP in accordance with https://github.com/smogon/pokemon-showdown/commit/3a79664eec49d30dcf414a04e2d1cacf7cc8facb
> Make Hard Press 100BP

- src/js/shared_controls.js
More of a minor coding style improvement rather than a bug fix or feature addition
> Don't put multiple attributes of an object on the same line

- calc/src/mechanics/gen789.ts
Fixes https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/post-10315730
> Physical Shell Side Arm should make contact

- calc/src/mechanics/gen789.ts
> Move Punching Glove base power modification to same block as other items

- calc/src/desc.ts
Fixes https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/page-41#post-10432937
> Fix Bad Dreams calc over multiple turns
